<?php
namespace Eden\Type;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    public function testType()
    {
		$class = eden('type')->type();
		$this->assertInstanceOf('Eden\\Type\\Type', $class);
		
		$class = eden('type')->type('something');
		$this->assertInstanceOf('Eden\\Type\\Type\\StringType', $class);
		
		$class = eden('type')->type(1, 2, 3);
		$this->assertInstanceOf('Eden\\Type\\Type\\ArrayType', $class);
    }
    
}
